routes/web.php
<?php
// Frontend
use App\Http\Controllers\AppController;
use App\Http\Controllers\Auth\EmailVerificationNotificationController;
use App\Http\Controllers\Auth\VerifyEmailController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\UriController;

// Backend
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ProductsController;
use App\Http\Controllers\Backend\UsersController;
use App\Http\Controllers\Backend\CategorysController;
use App\Http\Controllers\Backend\VendorsController;
use App\Http\Controllers\Backend\BlogsController;
use App\Http\Controllers\Backend\BlogcategoriesController;
use App\Http\Controllers\Backend\BlogtagsController;
use App\Http\Controllers\Backend\ProducttagsController;
use App\Http\Controllers\Backend\AttributesController;
use App\Http\Controllers\Backend\AttributesvaluesController;
use App\Http\Controllers\Backend\FileManagerController;
use App\Http\Controllers\Backend\UploadController;

use App\Http\Controllers\Backend\OrderController as BackendOrderController;
use App\Http\Controllers\Backend\ShippingOptionController;
use App\Http\Controllers\Backend\SettingGeneralController;
use App\Http\Controllers\Backend\PageController;
use App\Http\Controllers\Backend\TaxOptionController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Backend
Route::group(['prefix' => 'backend', 'as' => 'backend.', 'middleware' => ['auth', 'admin']], function ()
{
	Route::group(['prefix' => 'setting'], function () {
		// tax
		Route::resource('/tax', TaxOptionController::class);
		// // shipping
		Route::resource('/shipping', ShippingOptionController::class);
		// // // general
		Route::resource('/general', SettingGeneralController::class);
	});
	// page
	Route::resource('/page', PageController::class);

	//uploads
	Route::group(['prefix' => 'filemanager', 'as' => 'filemanager.'], function ()
	{
		Route::get('/', [UploadController::class, 'index'])->name('list');
		Route::middleware('optimizeImages')->group(function () {
			// all images will be optimized automatically
			// Route::post('upload-images', 'UploadController@index');
			Route::post('/upload', [UploadController::class, 'upload'])->name('upload');
			Route::post('/ajaxupload', [UploadController::class, 'ajaxupload'])->name('ajaxupload');
			Route::post('/store', [UploadController::class, 'store'])->name('store');
		});
		// Route::post('/upload', [UploadController::class, 'upload'])->name('upload');
		Route::get('/get_filemanager', [UploadController::class, 'get_filemanager'])->name('get_filemanager');
		Route::get('/files', [UploadController::class, 'getUploadedFile'])->name('getUploadedFile');
		Route::put('/update/{product}', [UploadController::class, 'update'])->name('update');
		Route::get('/get', [UploadController::class, 'get'])->name('get');
		Route::get('/getUploadedAssetsId', [UploadController::class, 'getUploadedAssetsId'])->name('getUploadedAssetsId');
	});

	Route::group(['prefix' => 'file', 'as' => 'file.'], function() {
		Route::get('/', [FileManagerController::class, 'index'])->name('index');
		Route::get('/show', [FileManagerController::class, 'show'])->name('show');
		Route::post('/store', [FileManagerController::class, 'store'])->name('store');
		Route::post('/destroy/{id}', [FileManagerController::class, 'destroy'])->name('destroy');
	});

	//products routes
	Route::group(['prefix' => 'products', 'as' => 'products.'], function ()
	{
		Route::get('/', [ProductsController::class, 'index'])->name('list');
		Route::get('/trash', [ProductsController::class, 'trash'])->name('trash');
		Route::get('/trash/recover/{id}', [ProductsController::class, 'recover'])->name('recover');
		Route::get('/create', [ProductsController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [ProductsController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [ProductsController::class, 'update'])->name('update');
		Route::post('/store', [ProductsController::class, 'store'])->name('store');
		Route::get('/delete/{id}', [ProductsController::class, 'destroy'])->name('delete');
		Route::get('/get', [ProductsController::class, 'get'])->name('get');
		Route::put('/update_digital_assets/{id}', [ProductsController::class, 'update_digital_assets'])->name('update_digital_assets');
		Route::put('/update_variant_assets/{id}', [ProductsController::class, 'update_variant_assets'])->name('update_variant_assets');
	});

	//users routes
	Route::group(['prefix' => 'users', 'as' => 'users.'], function ()
	{
		Route::get('/', [UsersController::class, 'index'])->name('list');
		Route::get('/create', [UsersController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [UsersController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [UsersController::class, 'update'])->name('update');
		Route::post('/store', [UsersController::class, 'store'])->name('store');
		Route::get('/get', [UsersController::class, 'get'])->name('get');
	});

	Route::group(['prefix' => 'customers', 'as' => 'customers.'], function ()
	{
		Route::get('/', [UsersController::class, 'customers'])->name('list');
	});

	//categories routes
	Route::group(['prefix' => 'products/categories', 'as' => 'products.categories.'], function ()
	{
		Route::get('/', [CategorysController::class, 'index'])->name('list');
		Route::get('/create', [CategorysController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [CategorysController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [CategorysController::class, 'update'])->name('update');
		Route::get('/delete/{id}', [CategorysController::class, 'destroy'])->name('delete');
		Route::post('/store', [CategorysController::class, 'store'])->name('store');
		Route::get('/get', [CategorysController::class, 'get'])->name('get');
	});

	//attributes routes
	Route::group(['prefix' => 'products/attributes', 'as' => 'products.attributes.'], function ()
	{
		Route::get('/', [AttributesController::class, 'index'])->name('list');
		Route::get('/create', [AttributesController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [AttributesController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [AttributesController::class, 'update'])->name('update');
		Route::post('/store', [AttributesController::class, 'store'])->name('store');
		Route::post('/get_for_variants', [AttributesController::class, 'ajaxcall'])->name('ajaxcall');
		Route::post('/get_combinations', [AttributesController::class, 'combinations'])->name('combinations');
		Route::get('/get', [AttributesController::class, 'get'])->name('get');
		Route::post('/get/values', [AttributesController::class, 'getvalues'])->name('getvalues');
		Route::get('/get_product_attribute', [AttributesController::class, 'getProductAttribute'])->name('getproductattribute');
	});

	Route::group(['prefix' => 'products/attributes/{id_attribute}/values', 'as' => 'products.attributes.values.'], function ()
	{
		Route::get('/', [AttributesvaluesController::class, 'index'])->name('list');
		Route::get('/create', [AttributesvaluesController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [AttributesvaluesController::class, 'edit'])->name('edit');
		Route::put('/update/{id}', [AttributesvaluesController::class, 'update'])->name('update');
		Route::post('/store', [AttributesvaluesController::class, 'store'])->name('store');
		Route::get('/get', [AttributesvaluesController::class, 'get'])->name('get');
	});

	Route::group(['prefix' => 'sellers', 'as' => 'sellers.'], function ()
	{
		Route::get('/', [VendorsController::class, 'index'])->name('list');
		Route::get('/create', [VendorsController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [VendorsController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [VendorsController::class, 'update'])->name('update');
		Route::post('/store', [VendorsController::class, 'store'])->name('store');
		Route::get('/get', [VendorsController::class, 'get'])->name('get');
	});

	//posts routes
	Route::group(['prefix' => 'blog/posts', 'as' => 'posts.'], function ()
	{
		Route::get('/', [BlogsController::class, 'index'])->name('list');
		Route::get('/trash', [BlogsController::class, 'trash'])->name('trash');
		Route::get('/trash/recover/{id}', [BlogsController::class, 'recover'])->name('recover');
		Route::get('/create', [BlogsController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [BlogsController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [BlogsController::class, 'update'])->name('update');
		Route::post('/store', [BlogsController::class, 'store'])->name('store');
		Route::get('/delete/{id}', [BlogsController::class, 'destroy'])->name('delete');
		Route::get('/get', [BlogsController::class, 'get'])->name('get');
	});

	//posts routes
	Route::group(['prefix' => 'blog/categories', 'as' => 'blog.categories.'], function ()
	{
		Route::get('/', [BlogcategoriesController::class, 'index'])->name('list');
		Route::get('/create', [BlogcategoriesController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [BlogcategoriesController::class, 'edit'])->name('edit');
		Route::get('/delete/{id}', [BlogcategoriesController::class, 'destroy'])->name('delete');
		Route::put('/update/{product}', [BlogcategoriesController::class, 'update'])->name('update');

app/Http/Controllers/Backend/BlogsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\BlogPost;
use App\Models\BlogTags;
use App\Http\Requests\PostStoreRequest;
use App\Models\BlogCategorie;
use App\Models\BlogPostTag;
use App\Models\BlogPostCategorie;
use Auth;

class BlogsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {      
        return view('backend.blog.posts.list', [
            'posts' => BlogPost::with(['categories', 'postauthor'])->orderBy('id', 'DESC')->get()
        ]);
    }

    public function trash()
    {
        return view('backend.blog.posts.trash', [
            'posts' => BlogPost::onlyTrashed()->orderBy('id', 'DESC')->get()
        ]);
    }

    public function get()
    {
        return datatables()->of(BlogPost::query())
        ->addIndexColumn()
        ->editColumn('cover_image', function($row) {
            return "<img src='".$row->cover_image."'>"; 
        })
        ->addColumn('action', function($row){

               $btn = '<a href="'.route('backend.posts.edit', $row->id).'"  class="edit btn btn-info btn-sm">Edit</a>';
               $btn = $btn.'<a href="javascript:void(0)" class="edit btn btn-danger btn-sm">Delete</a>';

                return $btn;
        })
        ->rawColumns(['action', 'cover_image'])
        ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.blog.posts.create',[
            'categories' => BlogCategorie::all(),
            'tags' => BlogTags::all()
        ]);
    }

    private function generateSlug($string)
    {
        return str_replace(' ', '-', $string);
    }

    private function registerNewTag($tag)
    {
        $blogtag = BlogTags::create([
            'name' => $tag,
            'slug' => $this->slugify($tag),
        ]);
        return $blogtag->id;
    }
    public function slugify($text, string $divider = '-')
    {
    // replace non letter or digits by divider
    $text = preg_replace('~[^\pL\d]+~u', $divider, $text);

    // transliterate
    $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);

    // remove unwanted characters
    $text = preg_replace('~[^-\w]+~', '', $text);

    // trim
    $text = trim($text, $divider);

    // remove duplicate divider
    $text = preg_replace('~-+~', $divider, $text);

    // lowercase
    $text = strtolower($text);

    if (empty($text)) {
        return 'n-a';
    }

    return $text;
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostStoreRequest $request)
    {
        $slug_count = BlogPost::whereName($request->name)->count();
        $suffix = ($slug_count == 0) ? '' : '-'.(string)$slug_count+1;
        $tags = (array)$request->input('tags');
        $categories = (array)$request->input('categories');
        $blog = new BlogPost();
        $data = $request->input();
        $data['author_id'] = Auth::id();

        if (BlogPost::where('slug', $this->slugify($request->name))->count()) {
            $data['slug'] = $this->slugify($request->name) . "-1";
        } else {
            $data['slug'] = $this->slugify($request->name);
        }

        $post_id = $blog->create($data)->id;
        foreach( $tags as $tag )
        {
            $id_tag = (!is_numeric($tag)) ? $this->registerNewTag($tag) : $tag;
            BlogPostTag::create([
                'id_tag' => $id_tag,
                'id_post' => $post_id
             ]);

        }

        foreach( $categories as $categorie )
        {
            BlogPostCategorie::create([
                'id_category' => $categorie,
                'id_post' => $post_id
             ]);
        }
        
        return redirect()->route('backend.posts.edit', $post_id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('backend.blog.posts.edit', [
            'post' => BlogPost::whereId($id)->with(['tags', 'categories', 'uploads'])->firstOrFail(),
            'categories' => BlogCategorie::all(),
            'tags' => BlogTags::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostStoreRequest $request, $id)
    {
        $slug_count = BlogPost::whereName($request->name)->count();
        $suffix = ($slug_count == 0) ? '' : '-'.(string)$slug_count+1;

        $tags = (array)$request->input('tags');
        $categories = (array)$request->input('categories');
        
        $blog = BlogPost::findOrFail($id);
        $data = $request->input();
        $data['author_id'] = Auth::id();

        $slug = $request->slug;

        if ($slug == '') {
            $slug = $request->name;
        }
        
        if (BlogPost::where('slug', $this->slugify($slug))->count()) {
            $data['slug'] = $this->slugify($slug) . "-1";
        } else {
            $data['slug'] = $this->slugify($slug);
        }    

        $blog->update($data);

        BlogPostTag::where('id_post', $blog->id)->delete();
        BlogPostCategorie::where('id_post', $blog->id)->delete();

        foreach( $tags as $tag )
        {
            $id_tag = (!is_numeric($tag)) ? $this->registerNewTag($tag) : $tag;
            BlogPostTag::create([
                'id_tag' => $id_tag,
                'id_post' => $blog->id
             ]);
        }

        foreach( $categories as $categorie )
        {
            BlogPostCategorie::create([
                'id_category' => $categorie,
                'id_post' =>  $blog->id
             ]);
        }
        return redirect()->route('backend.posts.edit', $blog->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        BlogPost::whereId($id)->delete();
        return redirect()->route('backend.posts.list');

    }

    public function recover($id)
    {
        BlogPost::withTrashed()->find($id)->restore();
        return redirect()->route('backend.posts.trash');
    }
}

resources/views/backend/blog/posts/list.blade.php
@extends('backend.layouts.app', ['activePage' => 'posts', 'title' => 'All Post', 'navName' => 'allpost', 'activeButton' => 'blog'])

@section('content')

<!-- Page Header -->
<div class="page-header mb-4">
    <nav aria-label="breadcrumb">
		<ol class="breadcrumb breadcrumb-no-gutter">
			<li class="breadcrumb-item"><a class="breadcrumb-link" href="{{ route('backend.users.list') }}">Users</a></li>
			<li class="breadcrumb-item active" aria-current="page">All Users</li>
		</ol>
	</nav>
    <div class="row align-items-center mb-3">
        <div class="col-sm mb-2 mb-sm-0">
            <h1 class="page-header-title">Post <span class="badge bg-soft-dark text-dark ms-2">72,031</span></h1>
        </div>
        <!-- End Col -->

        <div class="col-sm-auto">
            <a class="btn btn-primary" href="{{ route('backend.posts.create') }}">Create post</a>
        </div>
        <!-- End Col -->
    </div>
    <!-- End Row -->
</div>
<!-- End Page Header -->

<div class="row">
    <div class="col-md-12">
        <div class="card rounded-0">
            <div class="datatable-custom position-relative">

                    <table class="table table-lg table-thead-bordered table-nowrap table-align-middle card-table dataTable table-responsive no-footer">
                        <thead class="thead-light">
                            <th class="sorting_disabled" aria-label="">
                                <div class="form-checkbox">
                                    <input class="form-check-input" type="checkbox" value="" id="datatableCheckAll">
                                    <label class="form-check-label" for="datatableCheckAll"></label>
                                </div>
                            </th>
                            <th>ID</th>
                            <th>Name</th>
                            <!--<th>Slug</th>-->
                            <th>Author</th>
                            <th>Categories</th>
                            <th>Actions</th>
                        </thead>

                        <tbody>
                            @foreach ($posts as $post)
                            <tr>
                            <td class="table-column-pe-0">
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="ordersCheck1">
                                    <label class="form-check-label" for="ordersCheck1"></label>
                                </div>
                            </td>
                            <td>{{ $post->id }}</td>
                            <td>{{ $post->name }}</td>
                            <!--<td>{{ $post->slug }}</td>-->
                            <td>{{ $post->postauthor->name }}</td>
                            <td>
                                @foreach($post->categories as $category_info)
                                    <p><span class="badge btn-info"> {{$category_info->category->category_name}} </span>  </p>
                                @endforeach
                            </td>
                            <td>
                                <div class="btn-group" role="group">
                                    <a class="btn btn-dark btn-sm" href="{{ route('backend.posts.edit', $post->id) }}">Edit</a>
                                    <!-- Button Group -->
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-dark btn-icon btn-sm dropdown-toggle dropdown-toggle-empty" id="ordersExportDropdown1" data-bs-toggle="dropdown" aria-expanded="false"></button>
                                        <div class="dropdown-menu dropdown-menu-end mt-1" aria-labelledby="ordersExportDropdown1" style="">
                                            <span class="dropdown-header">Options</span>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item text-danger" onclick="return confirm('Are you sure you want to delete this post?')" href="{{route('backend.posts.delete', $post->id)}}">Delete</a>
                                        </div>
                                    </div>
                                    <!-- End Unfold -->
                                </div>
                                <!-- End Button -->

                            </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                
            </div>
        </div>
    </div>


</div>

@endsection

@section('js_content')
    <script>
        $(function() {

            $('.table').DataTable({
                processing: true,
                serverSide: true,
                bAutoWidth: false,

                ajax: '{{ route('backend.posts.get') }}',
                columns: [{
                        data: 'id',
                        name: 'id'
                    },
                   
                    {
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'slug',
                        name: 'slug'
                    },
                    {
                        data: 'categorie_id',
                        name: 'categorie_id'
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ]
            });
        });
    </script>
@endsection

resources/views/backend/blog/posts/trash.blade.php
@extends('backend.layouts.app', ['activePage' => 'posts', 'title' => 'All Post', 'navName' => 'blogtrash', 'activeButton' => 'blog'])

@section('content')
<div class="page-header">
    <div class="row align-items-center mb-3">
        <div class="col-sm mb-2 mb-sm-0">
            <h1 class="page-header-title">Trash <span class="badge bg-soft-dark text-dark ms-2">72,031</span></h1>
        </div>
        <!-- End Col -->
    </div>
    <!-- End Row -->
</div>


            <div class="row">
                <div class="col-md-12">
                    <div class="card rounded-0">
                        <div class="datatable-custom position-relative">
                                <table class="table table-lg table-thead-bordered table-nowrap table-align-middle card-table dataTable table-hover no-footer table-responsive">
                                    <thead class="thead-light">
                                        <th class="table-column-pe-0 sorting_disabled" aria-label="">
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" value="" id="datatableCheckAll">
                                                <label class="form-check-label" for="datatableCheckAll"></label>
                                            </div>
                                        </th>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Slug</th>
                                        <th>Author</th>
                                        <th>Categories</th>
                                        <th>Actions</th>
                                    </thead>

                                    <tbody>
                                        @foreach ($posts as $post)
                                        <tr>
                                        <td class="table-column-pe-0">
                                            <div class="form-check">
                                                <input type="checkbox" class="form-check-input" id="ordersCheck1">
                                                <label class="form-check-label" for="ordersCheck1"></label>
                                            </div>
                                        </td>
                                        <td>{{ $post->id }}</td>
                                       
                                        <td>{{ $post->name }}</td>
                                        <td>{{ $post->slug }}</td>
                                        <td>{{ $post->postauthor->name }}</td>
                                        <td>
                                            @foreach($post->categories as $category_info)
                                                <p><span class="badge btn-info"> {{$category_info->category->category_name}} </span>  </p>
                                            @endforeach
                                        </td>
                                        <td>
                                                <a class="btn btn-dark btn-sm" href="{{ route('backend.posts.recover', $post->id)}}"> <i class="bi-restore"></i> Restore </a>
                                              
                                        </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                         
                        </div>
                    </div>
                </div>
            </div>

@endsection

@section('js_content')
    <script>
        $(function() {

            $('.table').DataTable({
                processing: true,
                serverSide: true,
                bAutoWidth: false,

                ajax: '{{ route('backend.posts.get') }}',
                columns: [{
                        data: 'id',
                        name: 'id'
                    },
                   
                    {
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'slug',
                        name: 'slug'
                    },
                    {
                        data: 'categorie_id',
                        name: 'categorie_id'
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ]
            });
        });
    </script>
@endsection