routes/web.php
<?php
// Frontend
use App\Http\Controllers\AppController;
use App\Http\Controllers\Auth\EmailVerificationNotificationController;
use App\Http\Controllers\Auth\VerifyEmailController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\UriController;

// Backend
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ProductsController;
use App\Http\Controllers\Backend\UsersController;
use App\Http\Controllers\Backend\CategorysController;
use App\Http\Controllers\Backend\VendorsController;
use App\Http\Controllers\Backend\BlogsController;
use App\Http\Controllers\Backend\BlogcategoriesController;
use App\Http\Controllers\Backend\BlogtagsController;
use App\Http\Controllers\Backend\ProducttagsController;
use App\Http\Controllers\Backend\AttributesController;
use App\Http\Controllers\Backend\AttributesvaluesController;
use App\Http\Controllers\Backend\FileManagerController;
use App\Http\Controllers\Backend\UploadController;

use App\Http\Controllers\Backend\OrderController as BackendOrderController;
use App\Http\Controllers\Backend\ShippingOptionController;
use App\Http\Controllers\Backend\SettingGeneralController;
use App\Http\Controllers\Backend\PageController;
use App\Http\Controllers\Backend\TaxOptionController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Backend
Route::group(['prefix' => 'backend', 'as' => 'backend.', 'middleware' => ['auth', 'admin']], function ()
{
	Route::group(['prefix' => 'setting'], function () {
		// tax
		Route::resource('/tax', TaxOptionController::class);
		// // shipping
		Route::resource('/shipping', ShippingOptionController::class);
		// // // general
		Route::resource('/general', SettingGeneralController::class);
	});
	// page
	Route::resource('/page', PageController::class);

	//uploads
	Route::group(['prefix' => 'filemanager', 'as' => 'filemanager.'], function ()
	{
		Route::get('/', [UploadController::class, 'index'])->name('list');
		Route::middleware('optimizeImages')->group(function () {
			// all images will be optimized automatically
			// Route::post('upload-images', 'UploadController@index');
			Route::post('/upload', [UploadController::class, 'upload'])->name('upload');
			Route::post('/ajaxupload', [UploadController::class, 'ajaxupload'])->name('ajaxupload');
			Route::post('/store', [UploadController::class, 'store'])->name('store');
		});
		// Route::post('/upload', [UploadController::class, 'upload'])->name('upload');
		Route::get('/get_filemanager', [UploadController::class, 'get_filemanager'])->name('get_filemanager');
		Route::get('/files', [UploadController::class, 'getUploadedFile'])->name('getUploadedFile');
		Route::put('/update/{product}', [UploadController::class, 'update'])->name('update');
		Route::get('/get', [UploadController::class, 'get'])->name('get');
		Route::get('/getUploadedAssetsId', [UploadController::class, 'getUploadedAssetsId'])->name('getUploadedAssetsId');
	});

	Route::group(['prefix' => 'file', 'as' => 'file.'], function() {
		Route::get('/', [FileManagerController::class, 'index'])->name('index');
		Route::get('/show', [FileManagerController::class, 'show'])->name('show');
		Route::post('/store', [FileManagerController::class, 'store'])->name('store');
		Route::post('/destroy/{id}', [FileManagerController::class, 'destroy'])->name('destroy');
	});

	//products routes
	Route::group(['prefix' => 'products', 'as' => 'products.'], function ()
	{
		Route::get('/', [ProductsController::class, 'index'])->name('list');
		Route::get('/trash', [ProductsController::class, 'trash'])->name('trash');
		Route::get('/trash/recover/{id}', [ProductsController::class, 'recover'])->name('recover');
		Route::get('/create', [ProductsController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [ProductsController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [ProductsController::class, 'update'])->name('update');
		Route::post('/store', [ProductsController::class, 'store'])->name('store');
		Route::get('/delete/{id}', [ProductsController::class, 'destroy'])->name('delete');
		Route::get('/get', [ProductsController::class, 'get'])->name('get');
		Route::put('/update_digital_assets/{id}', [ProductsController::class, 'update_digital_assets'])->name('update_digital_assets');
		Route::put('/update_variant_assets/{id}', [ProductsController::class, 'update_variant_assets'])->name('update_variant_assets');
	});

	//users routes
	Route::group(['prefix' => 'users', 'as' => 'users.'], function ()
	{
		Route::get('/', [UsersController::class, 'index'])->name('list');
		Route::get('/create', [UsersController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [UsersController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [UsersController::class, 'update'])->name('update');
		Route::post('/store', [UsersController::class, 'store'])->name('store');
		Route::get('/get', [UsersController::class, 'get'])->name('get');
	});

	Route::group(['prefix' => 'customers', 'as' => 'customers.'], function ()
	{
		Route::get('/', [UsersController::class, 'customers'])->name('list');
	});

	//categories routes
	Route::group(['prefix' => 'products/categories', 'as' => 'products.categories.'], function ()
	{
		Route::get('/', [CategorysController::class, 'index'])->name('list');
		Route::get('/create', [CategorysController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [CategorysController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [CategorysController::class, 'update'])->name('update');
		Route::get('/delete/{id}', [CategorysController::class, 'destroy'])->name('delete');
		Route::post('/store', [CategorysController::class, 'store'])->name('store');
		Route::get('/get', [CategorysController::class, 'get'])->name('get');
	});

	//attributes routes
	Route::group(['prefix' => 'products/attributes', 'as' => 'products.attributes.'], function ()
	{
		Route::get('/', [AttributesController::class, 'index'])->name('list');
		Route::get('/create', [AttributesController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [AttributesController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [AttributesController::class, 'update'])->name('update');
		Route::post('/store', [AttributesController::class, 'store'])->name('store');
		Route::post('/get_for_variants', [AttributesController::class, 'ajaxcall'])->name('ajaxcall');
		Route::post('/get_combinations', [AttributesController::class, 'combinations'])->name('combinations');
		Route::get('/get', [AttributesController::class, 'get'])->name('get');
		Route::post('/get/values', [AttributesController::class, 'getvalues'])->name('getvalues');
		Route::get('/get_product_attribute', [AttributesController::class, 'getProductAttribute'])->name('getproductattribute');
	});

	Route::group(['prefix' => 'products/attributes/{id_attribute}/values', 'as' => 'products.attributes.values.'], function ()
	{
		Route::get('/', [AttributesvaluesController::class, 'index'])->name('list');
		Route::get('/create', [AttributesvaluesController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [AttributesvaluesController::class, 'edit'])->name('edit');
		Route::put('/update/{id}', [AttributesvaluesController::class, 'update'])->name('update');
		Route::post('/store', [AttributesvaluesController::class, 'store'])->name('store');
		Route::get('/get', [AttributesvaluesController::class, 'get'])->name('get');
	});

	Route::group(['prefix' => 'sellers', 'as' => 'sellers.'], function ()
	{
		Route::get('/', [VendorsController::class, 'index'])->name('list');
		Route::get('/create', [VendorsController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [VendorsController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [VendorsController::class, 'update'])->name('update');
		Route::post('/store', [VendorsController::class, 'store'])->name('store');
		Route::get('/get', [VendorsController::class, 'get'])->name('get');
	});

	//posts routes
	Route::group(['prefix' => 'blog/posts', 'as' => 'posts.'], function ()
	{
		Route::get('/', [BlogsController::class, 'index'])->name('list');
		Route::get('/trash', [BlogsController::class, 'trash'])->name('trash');
		Route::get('/trash/recover/{id}', [BlogsController::class, 'recover'])->name('recover');
		Route::get('/create', [BlogsController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [BlogsController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [BlogsController::class, 'update'])->name('update');
		Route::post('/store', [BlogsController::class, 'store'])->name('store');
		Route::get('/delete/{id}', [BlogsController::class, 'destroy'])->name('delete');
		Route::get('/get', [BlogsController::class, 'get'])->name('get');
	});

	//posts routes
	Route::group(['prefix' => 'blog/categories', 'as' => 'blog.categories.'], function ()
	{
		Route::get('/', [BlogcategoriesController::class, 'index'])->name('list');
		Route::get('/create', [BlogcategoriesController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [BlogcategoriesController::class, 'edit'])->name('edit');
		Route::get('/delete/{id}', [BlogcategoriesController::class, 'destroy'])->name('delete');
		Route::put('/update/{product}', [BlogcategoriesController::class, 'update'])->name('update');

app/Models/Attribute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Attribute extends Model
{
    use HasFactory;
    protected $fillable= [
        'name',
        'type',
        'slug',
    ];

    public function values()
    {
        return $this->hasMany(AttributeValue::class, 'attribute_id' , 'id');
    }
}

app/Http/Controllers/Backend/AttributesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Attribute;
use App\Models\AttributeValue;
use App\Http\Requests\StoreAttributeRequest;
use App\Models\ProductsVariant;

class AttributesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.products.attributes.list',[
            'attributes' => Attribute::orderBy('id', 'DESC')->paginate(10)
        ]);
    }

    public function getvalues(Request $request)
    {
        $type = Attribute::find($request->id_attribute)->type;
        $values = AttributeValue::where('attribute_id', $request->id_attribute)->get();
        return view('backend.products.ajax.values', [
            'values' => $values,
            'type' => $type
        ]);
    }

    public function ajaxcall(Request $request)
    {
        
        $attributes = Attribute::whereIn('id', $request->input('attributes'))->with(['values'])->get();
        return view('backend.products.attributes.values.ajax', [
            'attributes' => $attributes
        ]);
    }

    private function make_combinations($arrays, $i = 0) {
        if (!isset($arrays[$i])) {
            return array();
        }
        if ($i == count($arrays) - 1) {
            return $arrays[$i];
        }
        
        // get combinations from subsequent arrays
        $tmp = self::make_combinations($arrays, $i + 1);
        
        $result = array();
    
        // concat each array from tmp with each element from $arrays[$i]
        foreach ($arrays[$i] as $v) {
            foreach ($tmp as $t) {
                
                $result[] = is_array($t) ? 
                    array_merge(array($v), $t) :
                    array($v, $t);
            }
        }
    
        return $result;
    }
    public function combinations(Request $request)
    {
        $values = AttributeValue::whereIn('id', $request->input('values'))->get();
        $groupped_values = $values->groupBy('attribute_id')->toArray();
        $table = [];
        $i = 0;
        foreach ($groupped_values as $value)
        {
            $table[$i] = [];
  
            foreach ($value as $data)
            {
                array_push($table[$i], $data['attribute_id']."-".$data['id']."-".$data['name']);
            }
            $i++;
        }

        $combined = $this->make_combinations($table);

        // $result = [];
        // if (isset($request->product_id)) {
        //     // remove the items on product variants
        //     $productVariants = ProductsVariant::where('product_id', $request->product_id)->get();

        //     $variantAttributeValues = [];

        //     foreach ($productVariants as $variant) {
        //         $variantAttributeValues[] = $variant->variant_attribute_value;
        //     }

        //     foreach ($combined as $value) {
        //         $combinedId = [];

        //         foreach ($value as $item) {
        //             $id = explode('-', $item);

        //             $combinedId[] = $id[1];
        //         }

        //         $combinedId = implode(',', $combinedId);

        //         if (!in_array($combinedId, $variantAttributeValues)) {
        //             $result[] = $value;
        //         }
        //     }
        // } else {
        //     $result = $combined;
        // }

        // $productVariant

        return view('backend.products.ajax.values', [
            'variants' => $combined,
            'product_id' => $request->product_id ? $request->product_id : 0,
            'isDigital' => $request->isDigital
        ]);
       
    }

    function getProductAttribute(Request $request) {
        return ProductsVariant::where('product_id', $request->product_id)->with('uploads', 'asset')->get();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAttributeRequest $request)
    {
        $data = $request->input();
        $data['slug'] = str_replace(" ","-", strtolower($request->name));
        Attribute::Create($data);
        return redirect()->route('backend.products.attributes.list');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('backend.products.attributes.edit',[
            'attribute' => Attribute::findOrFail($id),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreAttributeRequest $request, $id)
    {
        $data = $request->input();
        $data['slug'] = str_replace(" ","-", strtolower($request->name));
        $attribute = Attribute::findOrFail($id);
        $attribute->update($data);
        return redirect()->route('backend.products.attributes.list');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/products/attributes/values/ajax.blade.php
@foreach ($attributes as $attribute)
<option disabled> ---- Values for {{$attribute->name}} ---- </option>
    @foreach ($attribute->values as $value)
        <option value="{{ $value->id }}" @if(isset($values_selected) && in_array($value->id, $values_selected)) selected  @endif data-tokens="{{ $value->name }}">
            {{$attribute->name}} : {{ $value->name }}</option>
    @endforeach
@endforeach

resources/views/backend/products/attributes/values/list.blade.php
@extends('backend.layouts.app', ['activePage' => 'products', 'title' => 'Products Attributes', 'navName' => 'attributes', 'activeButton' => 'products'])

@section('content')
    <!-- Page Header -->
    <div class="page-header">
        <div class="row align-items-end">
            <h1 class="page-header-title"> Attribute Values for {{ $attribute->name }}</h1>
        </div>
        <!-- End Row -->
    </div>
    <!-- End Page Header -->



    <!-- Card -->
    <div class="row">
        <div class="col-lg-4">
            <div class="card mb-4">
                <div class="card-header card-header-content-md-between">
                    <div class="mb-2 mb-md-0">
                        <h3 class="card-header-title mb-0">Add Value</h3>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('backend.products.attributes.values.store', $attribute->id) }}" method="POST">
                        @csrf
                        @if ($errors->has('name'))
                            <div class="col-md-12 mb-2">
                                <span class="badge btn-danger col-md-12"> value name is required </span>
                            </div>
                        @endif
                        <div class="col-md-12 mb-2">
                            <label for="name">Name:</label>
                            <input type="text" name="name" id="name" value="" class="form-control">

                        </div>

                        @if($attribute->type != 0)
                        <div class="col-md-12 mb-2">
                            <label for="name">Value:</label>
                            @if($attribute->type == 1)
                            <input type="color" name="value" id="name" value="" class="form-control">
                            @elseif($attribute->type == 2)
                            <div class="imagePreview img-thumbnail p-2">
                                <img id="fileManagerPreview" src="" style="width: 100%">
                            </div>
                            <input type="hidden" name="value" id="image_value" value="" class="form-control">
                            <label class="btn text-primary mt-2 p-0" id="getFileManager">Select Image</label>
                            @else($attribute->type == 0)
                            <input type="text" name="value" id="name" value="" class="form-control">
                            @endif
                        </div>
                        @else
                            <input type="hidden" name="value" id="name" value="{{ $attribute->name }}" class="form-control">
                        @endif
                        <div class="col-md-12 mb-2">
                            <button type="submit" class="btn btn-primary col-md-12"> Add to {{ $attribute->name }} </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-lg-8">
            <div class="card mb-4">
                <div class="card-header card-header-content-md-between">
                    <div class="mb-2 mb-md-0">
                        <h3 class="card-header-title mb-0">{{ $attribute->name }}</h3>
                    </div>
                </div>
                <div class="datatable-custom position-relative">
                    <div id="datatable_wrapper" class="dataTables_wrapper no-footer">
                        <table id="datatable"
                            class="table table-lg table-borderless table-thead-bordered table-nowrap table-align-middle card-table dataTable no-footer table-responsive" role="grid" aria-describedby="datatable_info">
                            <thead class="thead-light">
                                <tr role="row">
                                    <th class="table-column-pe-0 sorting_disabled" aria-label="">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value=""
                                                id="datatableCheckAll">
                                            <label class="form-check-label" for="datatableCheckAll"></label>
                                        </div>
                                    </th>
                                    <th class="sorting" aria-label="">ID</th>
                                    <th class="sorting_disabled" tabindex="0" aria-controls="datatable" aria-label="Name: activate to sort column ascending">Name</th>
                                    <th class="sorting_disabled" tabindex="0" aria-controls="datatable" aria-label="Name: activate to sort column ascending">Slug</th>
                                    <th class="sorting_disabled" tabindex="0" aria-controls="datatable" aria-label="Name: activate to sort column ascending">Value</th>
                                    <th class="sorting_disabled"aria-label="">Actions</th>
                                </tr>
                            </thead>

                            <tbody>

                                @foreach ($values as $value)
                                    <tr>
                                        <td class="table-column-pe-0">
                                            <div class="form-check">
                                                <input type="checkbox" class="form-check-input" id="ordersCheck1">
                                                <label class="form-check-label" for="ordersCheck1"></label>
                                            </div>
                                        </td>
                                        <td> {{ $value->id }} </td>
                                        <td> {{ $value->name }} </td>
                                        <td> {{ $value->slug }} </td>
                                        <td>
                                            @if ($attribute->type == 1)
                                                <span class="h-20px w-20px d-block" style="background:{{$value->value}}"></span>
                                            @elseif($attribute->type == 2)
                                                <img class="" src="{{ $value->image ? $value->image->getImageOptimizedFullName() : ''}}" style="width:100px"/>
                                            @else
                                            {{ $value->name }}
                                            @endif
                                        </td>
                                        <td>
                                            <div class="btn-group" role="group">
                                                <a class="btn btn-dark btn-sm" href="{{ route('backend.products.attributes.values.edit', ['id_attribute' => $attribute->id , 'id' => $value->id]) }}">Edit</a>
                                                <!-- Button Group -->
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-dark btn-icon btn-sm dropdown-toggle dropdown-toggle-empty" id="ordersExportDropdown1" data-bs-toggle="dropdown" aria-expanded="false"></button>
                                                    <div class="dropdown-menu dropdown-menu-end mt-1" aria-labelledby="ordersExportDropdown1" style="">

                                                        <a class="dropdown-item text-danger" href="javascript:;">Delete</a>
                                                    </div>
                                                </div>
                                                <!-- End Unfold -->
                                            </div>
                                            <!-- End Button -->
                                        </td>

                                    </tr>
                                @endforeach

                            </tbody>
                        </table>
                        <div class="dataTables_info" id="datatable_info" role="status" aria-live="polite">Showing 1 to
                            15
                            of 24
                            entries</div>
                    </div>
                </div>

                <div class="card-footer">
                    <div class="row justify-content-center justify-content-sm-between align-items-sm-center">
                        <div class="col-sm mb-2 mb-sm-0">

                            <div class="col-sm-auto">
                                <div class="d-flex justify-content-center justify-content-sm-end">
                                    <!-- Pagination -->
                                    <nav id="datatablePagination" aria-label="Activity pagination">
                                        <div class="dataTables_paginate paging_simple_numbers" id="datatable_paginate">
                                            <ul id="datatable_pagination" class="pagination datatable-custom-pagination">
                                                <li class="paginate_item page-item disabled">
                                                    <a class="paginate_button previous page-link" aria-controls="datatable" data-dt-idx="0" tabindex="0" id="datatable_previous">
                                                <span aria-hidden="true">Prev</span>
                                                </a>
                                                </li>
                                                <li class="paginate_item page-item active"><a
                                                        class="paginate_button page-link" aria-controls="datatable"
                                                        data-dt-idx="1" tabindex="0">1</a></li>
                                                <li class="paginate_item page-item"><a class="paginate_button page-link"
                                                        aria-controls="datatable" data-dt-idx="2" tabindex="0">2</a>
                                                </li>
                                                <li class="paginate_item page-item"><a
                                                        class="paginate_button next page-link" aria-controls="datatable"
                                                        data-dt-idx="3" tabindex="0" id="datatable_next"><span
                                                            aria-hidden="true">Next</span></a></li>
                                            </ul>
                                        </div>
                                    </nav>
                                </div>
                            </div>
                            <!-- End Col -->
                        </div>
                        <!-- End Row -->
                    </div>
                </div>
            </div>
        </div>
    </div>

    </div>

    <div id="fileManagerContainer"></div>

    <!-- End Card -->
@endsection

@section('js_content')
    <script>
        $(document).ready(function() {
            $('#name').keyup(function() {
                var slug = $(this).val()

                if (slug.charAt(slug.length - 1) != " ") {
                    $('#slug').val(slug.replace(/\s+/g, '-').toLowerCase());
                }

            })
        })

        $('#getFileManager').click(function () {
            $.ajax({
                url: "{{ route('backend.file.show') }}",
                success: function (data) {
                    if (!$.trim($('#fileManagerContainer').html()))
                        $('#fileManagerContainer').html(data);

                    $('#fileManagerModal').modal('show');

                    const getSelectedItem = function (selectedId, filePath) {

                        $('#image_value').val(selectedId);
                        $('#fileManagerPreview').attr('src', filePath);
                    }

                    setSelectedItemsCB(getSelectedItem, $('#image_value').val() == '' ? [] : [$('#image_value').val()], false);
                }
            })
        });

    </script>
@endsection