routes/web.php
<?php
// Frontend
use App\Http\Controllers\AppController;
use App\Http\Controllers\Auth\EmailVerificationNotificationController;
use App\Http\Controllers\Auth\VerifyEmailController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\UriController;

// Backend
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ProductsController;
use App\Http\Controllers\Backend\UsersController;
use App\Http\Controllers\Backend\CategorysController;
use App\Http\Controllers\Backend\VendorsController;
use App\Http\Controllers\Backend\BlogsController;
use App\Http\Controllers\Backend\BlogcategoriesController;
use App\Http\Controllers\Backend\BlogtagsController;
use App\Http\Controllers\Backend\ProducttagsController;
use App\Http\Controllers\Backend\AttributesController;
use App\Http\Controllers\Backend\AttributesvaluesController;
use App\Http\Controllers\Backend\FileManagerController;
use App\Http\Controllers\Backend\UploadController;

use App\Http\Controllers\Backend\OrderController as BackendOrderController;
use App\Http\Controllers\Backend\ShippingOptionController;
use App\Http\Controllers\Backend\SettingGeneralController;
use App\Http\Controllers\Backend\PageController;
use App\Http\Controllers\Backend\TaxOptionController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Backend
Route::group(['prefix' => 'backend', 'as' => 'backend.', 'middleware' => ['auth', 'admin']], function ()
{
	Route::group(['prefix' => 'setting'], function () {
		// tax
		Route::resource('/tax', TaxOptionController::class);
		// // shipping
		Route::resource('/shipping', ShippingOptionController::class);
		// // // general
		Route::resource('/general', SettingGeneralController::class);
	});
	// page
	Route::resource('/page', PageController::class);

	//uploads
	Route::group(['prefix' => 'filemanager', 'as' => 'filemanager.'], function ()
	{
		Route::get('/', [UploadController::class, 'index'])->name('list');
		Route::middleware('optimizeImages')->group(function () {
			// all images will be optimized automatically
			// Route::post('upload-images', 'UploadController@index');
			Route::post('/upload', [UploadController::class, 'upload'])->name('upload');
			Route::post('/ajaxupload', [UploadController::class, 'ajaxupload'])->name('ajaxupload');
			Route::post('/store', [UploadController::class, 'store'])->name('store');
		});
		// Route::post('/upload', [UploadController::class, 'upload'])->name('upload');
		Route::get('/get_filemanager', [UploadController::class, 'get_filemanager'])->name('get_filemanager');
		Route::get('/files', [UploadController::class, 'getUploadedFile'])->name('getUploadedFile');
		Route::put('/update/{product}', [UploadController::class, 'update'])->name('update');
		Route::get('/get', [UploadController::class, 'get'])->name('get');
		Route::get('/getUploadedAssetsId', [UploadController::class, 'getUploadedAssetsId'])->name('getUploadedAssetsId');
	});

	Route::group(['prefix' => 'file', 'as' => 'file.'], function() {
		Route::get('/', [FileManagerController::class, 'index'])->name('index');
		Route::get('/show', [FileManagerController::class, 'show'])->name('show');
		Route::post('/store', [FileManagerController::class, 'store'])->name('store');
		Route::post('/destroy/{id}', [FileManagerController::class, 'destroy'])->name('destroy');
	});

	//products routes
	Route::group(['prefix' => 'products', 'as' => 'products.'], function ()
	{
		Route::get('/', [ProductsController::class, 'index'])->name('list');
		Route::get('/trash', [ProductsController::class, 'trash'])->name('trash');
		Route::get('/trash/recover/{id}', [ProductsController::class, 'recover'])->name('recover');
		Route::get('/create', [ProductsController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [ProductsController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [ProductsController::class, 'update'])->name('update');
		Route::post('/store', [ProductsController::class, 'store'])->name('store');
		Route::get('/delete/{id}', [ProductsController::class, 'destroy'])->name('delete');
		Route::get('/get', [ProductsController::class, 'get'])->name('get');
		Route::put('/update_digital_assets/{id}', [ProductsController::class, 'update_digital_assets'])->name('update_digital_assets');
		Route::put('/update_variant_assets/{id}', [ProductsController::class, 'update_variant_assets'])->name('update_variant_assets');
	});

	//users routes
	Route::group(['prefix' => 'users', 'as' => 'users.'], function ()
	{
		Route::get('/', [UsersController::class, 'index'])->name('list');
		Route::get('/create', [UsersController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [UsersController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [UsersController::class, 'update'])->name('update');
		Route::post('/store', [UsersController::class, 'store'])->name('store');
		Route::get('/get', [UsersController::class, 'get'])->name('get');
	});

	Route::group(['prefix' => 'customers', 'as' => 'customers.'], function ()
	{
		Route::get('/', [UsersController::class, 'customers'])->name('list');
	});

	//categories routes
	Route::group(['prefix' => 'products/categories', 'as' => 'products.categories.'], function ()
	{
		Route::get('/', [CategorysController::class, 'index'])->name('list');
		Route::get('/create', [CategorysController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [CategorysController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [CategorysController::class, 'update'])->name('update');
		Route::get('/delete/{id}', [CategorysController::class, 'destroy'])->name('delete');
		Route::post('/store', [CategorysController::class, 'store'])->name('store');
		Route::get('/get', [CategorysController::class, 'get'])->name('get');
	});

	//attributes routes
	Route::group(['prefix' => 'products/attributes', 'as' => 'products.attributes.'], function ()
	{
		Route::get('/', [AttributesController::class, 'index'])->name('list');
		Route::get('/create', [AttributesController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [AttributesController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [AttributesController::class, 'update'])->name('update');
		Route::post('/store', [AttributesController::class, 'store'])->name('store');
		Route::post('/get_for_variants', [AttributesController::class, 'ajaxcall'])->name('ajaxcall');
		Route::post('/get_combinations', [AttributesController::class, 'combinations'])->name('combinations');
		Route::get('/get', [AttributesController::class, 'get'])->name('get');
		Route::post('/get/values', [AttributesController::class, 'getvalues'])->name('getvalues');
		Route::get('/get_product_attribute', [AttributesController::class, 'getProductAttribute'])->name('getproductattribute');
	});

	Route::group(['prefix' => 'products/attributes/{id_attribute}/values', 'as' => 'products.attributes.values.'], function ()
	{
		Route::get('/', [AttributesvaluesController::class, 'index'])->name('list');
		Route::get('/create', [AttributesvaluesController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [AttributesvaluesController::class, 'edit'])->name('edit');
		Route::put('/update/{id}', [AttributesvaluesController::class, 'update'])->name('update');
		Route::post('/store', [AttributesvaluesController::class, 'store'])->name('store');
		Route::get('/get', [AttributesvaluesController::class, 'get'])->name('get');
	});

	Route::group(['prefix' => 'sellers', 'as' => 'sellers.'], function ()
	{
		Route::get('/', [VendorsController::class, 'index'])->name('list');
		Route::get('/create', [VendorsController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [VendorsController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [VendorsController::class, 'update'])->name('update');
		Route::post('/store', [VendorsController::class, 'store'])->name('store');
		Route::get('/get', [VendorsController::class, 'get'])->name('get');
	});

	//posts routes
	Route::group(['prefix' => 'blog/posts', 'as' => 'posts.'], function ()
	{
		Route::get('/', [BlogsController::class, 'index'])->name('list');
		Route::get('/trash', [BlogsController::class, 'trash'])->name('trash');
		Route::get('/trash/recover/{id}', [BlogsController::class, 'recover'])->name('recover');
		Route::get('/create', [BlogsController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [BlogsController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [BlogsController::class, 'update'])->name('update');
		Route::post('/store', [BlogsController::class, 'store'])->name('store');
		Route::get('/delete/{id}', [BlogsController::class, 'destroy'])->name('delete');
		Route::get('/get', [BlogsController::class, 'get'])->name('get');
	});

	//posts routes
	Route::group(['prefix' => 'blog/categories', 'as' => 'blog.categories.'], function ()
	{
		Route::get('/', [BlogcategoriesController::class, 'index'])->name('list');
		Route::get('/create', [BlogcategoriesController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [BlogcategoriesController::class, 'edit'])->name('edit');
		Route::get('/delete/{id}', [BlogcategoriesController::class, 'destroy'])->name('delete');
		Route::put('/update/{product}', [BlogcategoriesController::class, 'update'])->name('update');

resources/views/backend/layouts/navbars/navbar.blade.php
<!-- ========== HEADER ========== -->
<header class="navbar navbar-expand-lg py-3">
    <nav class="container-fluid">
        <a class="navbar-brand col-auto" href="https://jewelrycadfiles.com/backend">
            #JewelryCG
        </a>
        <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <!--<span class="navbar-toggler-icon"></span>-->
        <i class="bi bi-list nav-icon"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown menu-area">
                    <a class="nav-link active" href="https://jewelrycadfiles.com">Home</a>
                </li>
                <li class="nav-item dropdown menu-area">
                    <a class="nav-link" href="https://jewelrycadfiles.com/3d-models">3D Models</a>
                </li>                
            </ul>
        </div>
    </nav>
</header>

  <!-- ========== END HEADER ========== -->

resources/views/backend/layouts/navbars/sidebar.blade.php
<!-- Navbar Vertical -->
  <aside id="navbarSupportedContent" class="sidebar collapse col-lg-2 col-sm-12">
    <div class="navbar-vertical-container">
      <div class="navbar-vertical-footer-offset">

        <!-- Content -->
        <div class="navbar-vertical-content">
          <div id="navbarVerticalMenu" class="nav nav-pills nav-vertical card-navbar-nav">
            <div class="nav-item">
                <a class="nav-link nav-link-main " href="/backend" data-placement="left">
                  <i class="bi-house-door nav-icon"></i>
                  <span class="nav-link-title">{{ __("Dashboard") }}</span>
                </a>
              </div>

            <span class="dropdown-header">{{ __("Users Management") }}</span>

            <!-- Collapse -->
            <div class="navbar-nav nav-compact">

            </div>
            <div id="navbarVerticalMenuPagesMenu">
              <!-- Collapse -->
              <div class="nav-item">
                <a class="nav-link nav-link-main dropdown-toggle " href="#navbarVerticalMenuPagesUsersMenu" role="button" data-bs-toggle="collapse" data-bs-target="#navbarVerticalMenuPagesUsersMenu" aria-expanded="false" aria-controls="navbarVerticalMenuPagesUsersMenu">
                  <i class="bi-people nav-icon"></i>
                  <span class="nav-link-title">{{ __("Users") }} <span class="badge bg-primary rounded-pill ms-1">5</span></span>
                </a>

                <div id="navbarVerticalMenuPagesUsersMenu" class="nav-collapse collapse @if($activePage == 'users') show @endif" data-bs-parent="#navbarVerticalMenuPagesMenu">
                  <a class="nav-link " href="{{ route('backend.users.list') }}">{{ __("All Users") }}</a>
                  <a class="nav-link " href="{{ route('backend.customers.list') }}">{{ __("Customers") }}</a>
                  <a class="nav-link " href="{{ route('backend.sellers.list') }}">{{ __("Sellers") }} <span class="badge bg-primary rounded-pill ms-1">5</span></a>
                  <a class="nav-link " href="#">{{ __("Profile") }}</a>
                </div>
              </div>
              <!-- End Collapse -->

              <span class="dropdown-header mt-4">{{ __("Content") }}</span>

              <!-- Collapse -->
              <div class="nav-item">
                <a class="nav-link nav-link-main dropdown-toggle " href="#navbarVerticalMenuAllPostMenu" role="button" data-bs-toggle="collapse" data-bs-target="#navbarVerticalMenuAllPostMenu" aria-expanded="false" aria-controls="navbarVerticalMenuAllPostMenu">
                  <i class="bi bi-pin-angle-fill nav-icon"></i>
                  <span class="nav-link-title">{{ __("Post") }}</span>
                </a>

                <div id="navbarVerticalMenuAllPostMenu" class="nav-collapse collapse @if($activePage == 'posts') show @endif" data-bs-parent="#navbarVerticalMenuPagesMenu">
                  <a class="nav-link @if($navName == 'allpost') active @endif" href="{{ route('backend.posts.list') }}">{{ __("All Post") }}</a>
                  <a class="nav-link @if($navName == 'addpost') active @endif" href="{{ route('backend.posts.create') }}">{{ __("Create Post") }}</a>
                  <a class="nav-link @if($navName == 'blogcategories') active @endif" href="{{ route('backend.blog.categories.list') }}">{{ __("Categories") }}</a>
                  <a class="nav-link @if($navName == 'blogtags') active @endif" href="{{ route('backend.blog.tags.list') }}">{{ __("Tags") }}</a>
                  <a class="nav-link @if($navName == 'blogtrash') active @endif" href="{{ route('backend.posts.trash') }}">{{ __("Trash") }}</a>
                </div>
              </div>
              <!-- End Collapse -->

              <!-- Collapse -->
              <div class="nav-item">
                <a class="nav-link nav-link-main dropdown-toggle " href="#navbarVerticalMenuAllPagesMenu" role="button" data-bs-toggle="collapse" data-bs-target="#navbarVerticalMenuAllPagesMenu" aria-expanded="false" aria-controls="navbarVerticalMenuAllPagesMenu">
                  <i class="bi-stickies nav-icon"></i>
                  <span class="nav-link-title">{{ __("Pages") }}</span>
                </a>

                <div id="navbarVerticalMenuAllPagesMenu" class="nav-collapse collapse @if($activePage == 'page') show @endif" data-bs-parent="#navbarVerticalMenuPagesMenu">
                  <a class="nav-link " href="{{ route('backend.page.index') }}">{{ __("All Pages") }}</a>
                  <a class="nav-link " href="{{ route('backend.page.create') }}">{{ __("Add New") }}</a>
                </div>
              </div>
              <!-- End Collapse -->

              <div class="nav-item">
                <a class="nav-link nav-link-main @if($activePage == 'filemanager') collapse @endif" href="{{ route('backend.file.index')}}" data-placement="left">
                  <i class="bi-folder2-open nav-icon"></i>
                  <span class="nav-link-title">File Manager</span>
                </a>
              </div>

              <span class="dropdown-header mt-4">{{ __("Commerce") }}</span>

              <!-- Collapse -->
              <div class="nav-item">
                <a class="nav-link nav-link-main dropdown-toggle " href="#navbarVerticalMenuAllProductsMenu" role="button" data-bs-toggle="collapse" data-bs-target="#navbarVerticalMenuAllProductsMenu" aria-expanded="false" aria-controls="navbarVerticalMenuAllProductsMenu">
                  <i class="bi-basket nav-icon"></i>
                  <span class="nav-link-title">{{ __("Products") }}</span>
                </a>

                <div id="navbarVerticalMenuAllProductsMenu" class="nav-collapse collapse @if($activePage == 'products') show @endif" data-bs-parent="#navbarVerticalMenuPagesMenu">
                  <a class="nav-link @if($navName == 'allproducts') active @endif" href="{{ route('backend.products.list') }}">{{ __("All Products") }}</a>
                  <a class="nav-link @if($navName == 'addproduct') active @endif" href="{{ route('backend.products.create') }}">{{ __("Create Product") }}</a>
                  <a class="nav-link @if($navName == 'attributes') active @endif " href="{{route('backend.products.attributes.list')}}">{{ __("Attributes") }}</a>
                  <a class="nav-link @if($navName == 'productscategories') active @endif" href="{{ route('backend.products.categories.list') }}">{{ __("Categories") }}</a>
                  <a class="nav-link @if($navName == 'productstags') active @endif" href="{{ route('backend.products.tags.list') }}">{{ __("Tags") }}</a>
                  <a class="nav-link @if($navName == 'productstrash') active @endif" href="{{ route('backend.products.trash') }}">{{ __("Trash") }}</a>
                </div>
              </div>
              <!-- End Collapse -->

              <!-- Collapse -->
              <div class="nav-item">
                <a class="nav-link nav-link-main dropdown-toggle " href="#navbarVerticalMenuAllOrdersMenu" role="button" data-bs-toggle="collapse" data-bs-target="#navbarVerticalMenuAllOrdersMenu" aria-expanded="false" aria-controls="navbarVerticalMenuAllOrdersMenu">
                  <i class="bi bi-receipt nav-icon"></i>
                  <span class="nav-link-title">{{ __("Orders") }}</span>
                </a>

                <div id="navbarVerticalMenuAllOrdersMenu" class="nav-collapse collapse @if($activePage == 'orders') show @endif" data-bs-parent="#navbarVerticalMenuPagesMenu">
                  <a class="nav-link @if($navName == 'orderslist') active @endif" href="{{ route('backend.orders.list') }}">{{ __("All Orders") }}</a>
                  <a class="nav-link {{$navName}} @if($navName == 'ordersPending') active @endif" href="{{ route('backend.orders.pending') }}">{{ __("Pending") }} <span id="pendingBadge" class="badge bg-primary rounded-pill ms-1">{{ "" }}</span></a>
                </div>
              </div>
              <!-- End Collapse -->

              <div class="nav-item">
                <a class="nav-link nav-link-main " href="#" data-placement="left">
                  <i class="bi-folder2-open nav-icon"></i>
                  <span class="nav-link-title">Coupons</span>
                </a>
              </div>

              <div class="nav-item">
                <a class="nav-link nav-link-main " href="#" data-placement="left">
                  <i class="bi-folder2-open nav-icon"></i>
                  <span class="nav-link-title">Reports</span>
                </a>
              </div>

              <span class="dropdown-header mt-4">{{ __("Configuration") }}</span>

              <div class="nav-item">
                <a class="nav-link nav-link-main " href="{{ route('backend.tax.index') }}" data-placement="left">
                  <i class="bi-key nav-icon"></i>
                  <span class="nav-link-title @if($navName == 'tax') active @endif">Tax</span>
                </a>
              </div>

              <div class="nav-item">
                <a class="nav-link nav-link-main " href="{{ route('backend.shipping.index') }}" data-placement="left">
                  <i class="bi-key nav-icon"></i>
                  <span class="nav-link-title @if($navName == 'Shipping') active @endif">Shipping</span>
                </a>
              </div>

              <div class="nav-item">
                <a class="nav-link nav-link-main " href="{{ route('backend.general.index') }}" data-placement="left">
                  <i class="bi-key nav-icon"></i>
                  <span class="nav-link-title @if($navName == 'ordersPending') active @endif">General</span>
                </a>
              </div>

              <div class="nav-item">
                <a class="nav-link nav-link-main " href="#" data-placement="left">
                  <i class="bi-key nav-icon"></i>
                  <span class="nav-link-title @if($navName == 'ordersPending') active @endif">API Keys</span>
                </a>
              </div>

        </div>
        <!-- End Content -->

        <!-- Footer -->
        <div class="navbar-vertical-footer">
          <ul class="navbar-vertical-footer-list">
          </ul>
        </div>
        <!-- End Footer -->
      </div>
    </div>
  </aside>

  <!-- End Navbar Vertical -->

  <script>
    $(function() {
      $.ajax({
        url: "{{ url('backend/orders') }}",
        type: 'post',
        data: {
          "_token": "{{ csrf_token() }}",
          status: $(this).val()
        },
        success: function (data) {
          $("#pendingBadge").html(data);
        }
      })
    });
  </script>