routes/web.php
<?php
// Frontend
use App\Http\Controllers\AppController;
use App\Http\Controllers\Auth\EmailVerificationNotificationController;
use App\Http\Controllers\Auth\VerifyEmailController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\UriController;

// Backend
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ProductsController;
use App\Http\Controllers\Backend\UsersController;
use App\Http\Controllers\Backend\CategorysController;
use App\Http\Controllers\Backend\VendorsController;
use App\Http\Controllers\Backend\BlogsController;
use App\Http\Controllers\Backend\BlogcategoriesController;
use App\Http\Controllers\Backend\BlogtagsController;
use App\Http\Controllers\Backend\ProducttagsController;
use App\Http\Controllers\Backend\AttributesController;
use App\Http\Controllers\Backend\AttributesvaluesController;
use App\Http\Controllers\Backend\FileManagerController;
use App\Http\Controllers\Backend\UploadController;

use App\Http\Controllers\Backend\OrderController as BackendOrderController;
use App\Http\Controllers\Backend\ShippingOptionController;
use App\Http\Controllers\Backend\SettingGeneralController;
use App\Http\Controllers\Backend\PageController;
use App\Http\Controllers\Backend\TaxOptionController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Backend
Route::group(['prefix' => 'backend', 'as' => 'backend.', 'middleware' => ['auth', 'admin']], function ()
{
	Route::group(['prefix' => 'setting'], function () {
		// tax
		Route::resource('/tax', TaxOptionController::class);
		// // shipping
		Route::resource('/shipping', ShippingOptionController::class);
		// // // general
		Route::resource('/general', SettingGeneralController::class);
	});
	// page
	Route::resource('/page', PageController::class);

	//uploads
	Route::group(['prefix' => 'filemanager', 'as' => 'filemanager.'], function ()
	{
		Route::get('/', [UploadController::class, 'index'])->name('list');
		Route::middleware('optimizeImages')->group(function () {
			// all images will be optimized automatically
			// Route::post('upload-images', 'UploadController@index');
			Route::post('/upload', [UploadController::class, 'upload'])->name('upload');
			Route::post('/ajaxupload', [UploadController::class, 'ajaxupload'])->name('ajaxupload');
			Route::post('/store', [UploadController::class, 'store'])->name('store');
		});
		// Route::post('/upload', [UploadController::class, 'upload'])->name('upload');
		Route::get('/get_filemanager', [UploadController::class, 'get_filemanager'])->name('get_filemanager');
		Route::get('/files', [UploadController::class, 'getUploadedFile'])->name('getUploadedFile');
		Route::put('/update/{product}', [UploadController::class, 'update'])->name('update');
		Route::get('/get', [UploadController::class, 'get'])->name('get');
		Route::get('/getUploadedAssetsId', [UploadController::class, 'getUploadedAssetsId'])->name('getUploadedAssetsId');
	});

	Route::group(['prefix' => 'file', 'as' => 'file.'], function() {
		Route::get('/', [FileManagerController::class, 'index'])->name('index');
		Route::get('/show', [FileManagerController::class, 'show'])->name('show');
		Route::post('/store', [FileManagerController::class, 'store'])->name('store');
		Route::post('/destroy/{id}', [FileManagerController::class, 'destroy'])->name('destroy');
	});

	//products routes
	Route::group(['prefix' => 'products', 'as' => 'products.'], function ()
	{
		Route::get('/', [ProductsController::class, 'index'])->name('list');
		Route::get('/trash', [ProductsController::class, 'trash'])->name('trash');
		Route::get('/trash/recover/{id}', [ProductsController::class, 'recover'])->name('recover');
		Route::get('/create', [ProductsController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [ProductsController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [ProductsController::class, 'update'])->name('update');
		Route::post('/store', [ProductsController::class, 'store'])->name('store');
		Route::get('/delete/{id}', [ProductsController::class, 'destroy'])->name('delete');
		Route::get('/get', [ProductsController::class, 'get'])->name('get');
		Route::put('/update_digital_assets/{id}', [ProductsController::class, 'update_digital_assets'])->name('update_digital_assets');
		Route::put('/update_variant_assets/{id}', [ProductsController::class, 'update_variant_assets'])->name('update_variant_assets');
	});

	//users routes
	Route::group(['prefix' => 'users', 'as' => 'users.'], function ()
	{
		Route::get('/', [UsersController::class, 'index'])->name('list');
		Route::get('/create', [UsersController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [UsersController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [UsersController::class, 'update'])->name('update');
		Route::post('/store', [UsersController::class, 'store'])->name('store');
		Route::get('/get', [UsersController::class, 'get'])->name('get');
	});

	Route::group(['prefix' => 'customers', 'as' => 'customers.'], function ()
	{
		Route::get('/', [UsersController::class, 'customers'])->name('list');
	});

	//categories routes
	Route::group(['prefix' => 'products/categories', 'as' => 'products.categories.'], function ()
	{
		Route::get('/', [CategorysController::class, 'index'])->name('list');
		Route::get('/create', [CategorysController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [CategorysController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [CategorysController::class, 'update'])->name('update');
		Route::get('/delete/{id}', [CategorysController::class, 'destroy'])->name('delete');
		Route::post('/store', [CategorysController::class, 'store'])->name('store');
		Route::get('/get', [CategorysController::class, 'get'])->name('get');
	});

	//attributes routes
	Route::group(['prefix' => 'products/attributes', 'as' => 'products.attributes.'], function ()
	{
		Route::get('/', [AttributesController::class, 'index'])->name('list');
		Route::get('/create', [AttributesController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [AttributesController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [AttributesController::class, 'update'])->name('update');
		Route::post('/store', [AttributesController::class, 'store'])->name('store');
		Route::post('/get_for_variants', [AttributesController::class, 'ajaxcall'])->name('ajaxcall');
		Route::post('/get_combinations', [AttributesController::class, 'combinations'])->name('combinations');
		Route::get('/get', [AttributesController::class, 'get'])->name('get');
		Route::post('/get/values', [AttributesController::class, 'getvalues'])->name('getvalues');
		Route::get('/get_product_attribute', [AttributesController::class, 'getProductAttribute'])->name('getproductattribute');
	});

	Route::group(['prefix' => 'products/attributes/{id_attribute}/values', 'as' => 'products.attributes.values.'], function ()
	{
		Route::get('/', [AttributesvaluesController::class, 'index'])->name('list');
		Route::get('/create', [AttributesvaluesController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [AttributesvaluesController::class, 'edit'])->name('edit');
		Route::put('/update/{id}', [AttributesvaluesController::class, 'update'])->name('update');
		Route::post('/store', [AttributesvaluesController::class, 'store'])->name('store');
		Route::get('/get', [AttributesvaluesController::class, 'get'])->name('get');
	});

	Route::group(['prefix' => 'sellers', 'as' => 'sellers.'], function ()
	{
		Route::get('/', [VendorsController::class, 'index'])->name('list');
		Route::get('/create', [VendorsController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [VendorsController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [VendorsController::class, 'update'])->name('update');
		Route::post('/store', [VendorsController::class, 'store'])->name('store');
		Route::get('/get', [VendorsController::class, 'get'])->name('get');
	});

	//posts routes
	Route::group(['prefix' => 'blog/posts', 'as' => 'posts.'], function ()
	{
		Route::get('/', [BlogsController::class, 'index'])->name('list');
		Route::get('/trash', [BlogsController::class, 'trash'])->name('trash');
		Route::get('/trash/recover/{id}', [BlogsController::class, 'recover'])->name('recover');
		Route::get('/create', [BlogsController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [BlogsController::class, 'edit'])->name('edit');
		Route::put('/update/{product}', [BlogsController::class, 'update'])->name('update');
		Route::post('/store', [BlogsController::class, 'store'])->name('store');
		Route::get('/delete/{id}', [BlogsController::class, 'destroy'])->name('delete');
		Route::get('/get', [BlogsController::class, 'get'])->name('get');
	});

	//posts routes
	Route::group(['prefix' => 'blog/categories', 'as' => 'blog.categories.'], function ()
	{
		Route::get('/', [BlogcategoriesController::class, 'index'])->name('list');
		Route::get('/create', [BlogcategoriesController::class, 'create'])->name('create');
		Route::get('/edit/{id}', [BlogcategoriesController::class, 'edit'])->name('edit');
		Route::get('/delete/{id}', [BlogcategoriesController::class, 'destroy'])->name('delete');
		Route::put('/update/{product}', [BlogcategoriesController::class, 'update'])->name('update');

app/Http/Controllers/Backend/AttributesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Attribute;
use App\Models\AttributeValue;
use App\Http\Requests\StoreAttributeRequest;
use App\Models\ProductsVariant;

class AttributesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.products.attributes.list',[
            'attributes' => Attribute::orderBy('id', 'DESC')->paginate(10)
        ]);
    }

    public function getvalues(Request $request)
    {
        $type = Attribute::find($request->id_attribute)->type;
        $values = AttributeValue::where('attribute_id', $request->id_attribute)->get();
        return view('backend.products.ajax.values', [
            'values' => $values,
            'type' => $type
        ]);
    }

    public function ajaxcall(Request $request)
    {
        
        $attributes = Attribute::whereIn('id', $request->input('attributes'))->with(['values'])->get();
        return view('backend.products.attributes.values.ajax', [
            'attributes' => $attributes
        ]);
    }

    private function make_combinations($arrays, $i = 0) {
        if (!isset($arrays[$i])) {
            return array();
        }
        if ($i == count($arrays) - 1) {
            return $arrays[$i];
        }
        
        // get combinations from subsequent arrays
        $tmp = self::make_combinations($arrays, $i + 1);
        
        $result = array();
    
        // concat each array from tmp with each element from $arrays[$i]
        foreach ($arrays[$i] as $v) {
            foreach ($tmp as $t) {
                
                $result[] = is_array($t) ? 
                    array_merge(array($v), $t) :
                    array($v, $t);
            }
        }
    
        return $result;
    }
    public function combinations(Request $request)
    {
        $values = AttributeValue::whereIn('id', $request->input('values'))->get();
        $groupped_values = $values->groupBy('attribute_id')->toArray();
        $table = [];
        $i = 0;
        foreach ($groupped_values as $value)
        {
            $table[$i] = [];
  
            foreach ($value as $data)
            {
                array_push($table[$i], $data['attribute_id']."-".$data['id']."-".$data['name']);
            }
            $i++;
        }

        $combined = $this->make_combinations($table);

        // $result = [];
        // if (isset($request->product_id)) {
        //     // remove the items on product variants
        //     $productVariants = ProductsVariant::where('product_id', $request->product_id)->get();

        //     $variantAttributeValues = [];

        //     foreach ($productVariants as $variant) {
        //         $variantAttributeValues[] = $variant->variant_attribute_value;
        //     }

        //     foreach ($combined as $value) {
        //         $combinedId = [];

        //         foreach ($value as $item) {
        //             $id = explode('-', $item);

        //             $combinedId[] = $id[1];
        //         }

        //         $combinedId = implode(',', $combinedId);

        //         if (!in_array($combinedId, $variantAttributeValues)) {
        //             $result[] = $value;
        //         }
        //     }
        // } else {
        //     $result = $combined;
        // }

        // $productVariant

        return view('backend.products.ajax.values', [
            'variants' => $combined,
            'product_id' => $request->product_id ? $request->product_id : 0,
            'isDigital' => $request->isDigital
        ]);
       
    }

    function getProductAttribute(Request $request) {
        return ProductsVariant::where('product_id', $request->product_id)->with('uploads', 'asset')->get();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAttributeRequest $request)
    {
        $data = $request->input();
        $data['slug'] = str_replace(" ","-", strtolower($request->name));
        Attribute::Create($data);
        return redirect()->route('backend.products.attributes.list');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('backend.products.attributes.edit',[
            'attribute' => Attribute::findOrFail($id),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreAttributeRequest $request, $id)
    {
        $data = $request->input();
        $data['slug'] = str_replace(" ","-", strtolower($request->name));
        $attribute = Attribute::findOrFail($id);
        $attribute->update($data);
        return redirect()->route('backend.products.attributes.list');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public $pageTitle;

    public function __constuctor(){
        $this->pageTitle = "Home";
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.dashboard', [
            'title' => $this->pageTitle,
            'activePage' => "dashboard",
            'activeButton' => 'laravel'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/page/create.blade.php
@extends('backend.layouts.app', ['activePage' => 'page', 'title' => 'Create Page', 'navName' => 'addpost', 'activeButton' => 'blog'])

@section('content')
<div class="page-header">
    <div class="row align-items-end">
        <h1 class="page-header-title">Create page</h1>
    </div>
    <!-- End Row -->
</div>
    <form action="{{ route('backend.page.store') }}" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-8">
                @csrf
                <div class="card col-md-12 mb-4">
                    <!-- Header -->
                    <div class="card-header">
                        <h4 class="card-header-title mb-0">Page information</h4>
                    </div>
                    <!-- End Header -->
                    <div class="card-body">
                        @include('includes.validation-form')
                        <div class="mb-2">
                            <label for="name" class="w-100 mb-2">Name:</label>
                            <input type="text" name="name" id="name" value="{{ old('name') }}" class="form-control">
                        </div>
                        <div class="mb-2">
                            <label for="slug" class="w-100 mb-2">Slug:</label>
                            <input type="text" name="slug" id="slug" value="{{ old('slug') }}" class="form-control">
                        </div>
                        <div class="mb-2">
                            <label for="desc" class="w-100 mb-2">Post:</label>
                            <textarea name="post" id="desc" rows="6" class="form-control">{{ old('post') }}</textarea>
                        </div>
                    </div>
                </div>
                <div class="card col-md-12">
                    <!-- Header -->
                    <div class="card-header">
                        <h4 class="card-header-title mb-0">Meta information</h4>
                    </div>
                    <!-- End Header -->
                    <div class="card-body">
                        <div class="mb-2">
                            <label for="meta_title" class="w-100 mb-2">Meta Title:</label>
                            <input type="text" name="meta_title" id="meta_title" value="{{ old('meta_title') }}" class="form-control">
                        </div>
                        <div class="">
                            <label for="meta_description" class="w-100 mb-2">Meta Description:</label>
                            <textarea name="meta_description" id="meta_description" rows="6" class="form-control">{{ old('meta_description') }}</textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <!-- Card -->
                <div class="card mb-3 mb-4">
                    <!-- Header -->
                    <div class="card-header">
                        <h4 class="card-header-title mb-0">Organization</h4>
                    </div>
                    <!-- End Header -->

                    <!-- Body -->
                    <div class="card-body">
                        <div class="mb-4 col-12">
                            <div class="col-12">
                                <label class="mb-2" for="">Status</label>
                                <select class="selectpicker w-100" name="status">
                                    <option value="1" selected>Published</option>
                                    <option value="2" >Draft</option>
                                    <option value="3" >Pending Review</option>
                                </select>
                            </div>
                        </div>

                        <div class="mb-4 col-12">
                            <label for="category" class="w-100 mb-2">Parent</label>
                            <div class="col-12">
                                <select class="selectpicker " name="parent_id" data-live-search="true" data-container="body">
                                    <option value='0'>None</option>
                                    @foreach ($parents as $parent)
                                        <option value="{{$parent->id}}">{{$parent->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Card -->
            </div>
        </div>

        <div class="position-fixed start-50 bottom-0 translate-middle-x w-100 zi-99 mb-3" style="max-width: 40rem;">
        <!-- Card -->
        <div class="card card-sm bg-dark border-dark mx-2">
          <div class="card-body">
            <div class="row justify-content-center justify-content-sm-between">
              <div class="col">
                <button type="button" class="btn btn-danger">Cancel</button>
              </div>
              <!-- End Col -->

              <div class="col-auto">
                <div class="d-flex gap-3">
                  <button type="button" class="btn btn-light">Save Draft</button>
                  <button type="submit" class="btn btn-primary">Publish</button>
                </div>
              </div>
              <!-- End Col -->
            </div>
            <!-- End Row -->
          </div>
        </div>
        <!-- End Card -->
      </div>
    </form>
    <div id="fileManagerContainer"></div>

    <div id='ajaxCalls'>
    </div>
@endsection

@section('js_content')
    <script>
        $(document).ready(function() {
            $('#desc').trumbowyg();
            $('#meta_description').trumbowyg();
        })
        $(".imgAdd").click(function() {
            $(this).closest(".row").find('.imgAdd').before(
                '<div class="col-sm-2 imgUp"><div class="imagePreview"></div><label class="btn btn-primary">Upload<input type="file" class="uploadFile img" value="Upload Photo" style="width:0px;height:0px;overflow:hidden;"></label><i class="fa fa-times del"></i></div>'
            );
        });
        $(document).on("click", "i.del", function() {
            $(this).parent().remove();
        });
        $(function() {
            $(document).on("change", ".uploadFile", function() {
                var uploadFile = $(this);
                var files = !!this.files ? this.files : [];
                if (!files.length || !window.FileReader)
                    return; // no file selected, or no FileReader support

                if (/^image/.test(files[0].type)) { // only image file
                    var reader = new FileReader(); // instance of the FileReader
                    reader.readAsDataURL(files[0]); // read the local file

                    reader.onloadend = function() { // set image data as background of div
                        //alert(uploadFile.closest(".upimage").find('.imagePreview').length);
                        uploadFile.closest(".imgUp").find('.imagePreview').css("background-image",
                            "url(" + this.result + ")");
                    }
                }

            });

            $('.select2').select2({

            tags: true,
            maximumSelectionLength: 10,
            tokenSeparators: [','],
            placeholder: "Select or type keywords",
            })
        });


        $('#getFileManager').click(function () {
            $.ajax({
                url: "{{ route('backend.file.show') }}",
                success: function (data) {
                    if (!$.trim($('#fileManagerContainer').html()))
                        $('#fileManagerContainer').html(data);

                    $('#fileManagerModal').modal('show');

                    const getSelectedItem = function (selectedId, filePath) {

                        $('#fileManagerId').val(selectedId);
                        $('#fileManagerPreview').attr('src', filePath);
                    }

                    setSelectedItemsCB(getSelectedItem, $('#fileManagerId').val() == '' ? [] : [$('#fileManagerId').val()], false);
                }
            })
        });


    </script>
    <script src="{{ asset('assets/vendor/quill/dist/quill.min.js') }}"></script>
    <script src="{{ asset('assets/js/hs.quill.js') }}"></script>
    <script>
    (function() {
        // INITIALIZATION OF QUILLJS EDITOR
        // =======================================================
        HSCore.components.HSQuill.init('.js-quill')
    });
    </script>
@endsection

resources/views/backend/page/index.blade.php
@extends('backend.layouts.app', ['activePage' => 'page', 'title' => 'page', 'navName' => 'addproduct', 'activeButton' => 'catalogue'])

@section('content')
    <div class="page-header">
        <div class="row align-items-center mb-3">
            <div class="col-sm mb-2 mb-sm-0">
                <h1 class="page-header-title">Page <span class="badge bg-soft-dark text-dark ms-2"></span></h1>
            </div>
            <!-- End Col -->

            <div class="col-sm-auto">
                <a class="btn btn-primary" href="{{ route('backend.page.create') }}">Create Page</a>
            </div>
            <!-- End Col -->
        </div>
        <!-- End Row -->
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card strpied-tabled-with-hover rounded-0">
                <div class="datatable-custom">
                    <div class="col-md-12">
                        <table
                            class="table table-lg table-thead-bordered table-nowrap table-align-middle card-table dataTable table-hover table-responsive no-footer">
                            <thead class="thead-light">
                                <th class="sorting_disabled" aria-label="">
                                    <div class="form-checkbox">
                                        <input class="form-check-input" type="checkbox" value=""
                                            id="datatableCheckAll">
                                        <label class="form-check-label" for="datatableCheckAll"></label>
                                    </div>
                                </th>
                                <th class="sorting">ID</th>
                                <th>Name</th>
                                <th>Author</th>
                                <th>Actions</th>
                            </thead>
                            <tbody>
                                @php
                                  $nIndex = 0;
                                @endphp
                                @foreach ($pages as $page)
                                    <tr>
                                        <td class="table-column-pe-0">
                                            <div class="form-check">
                                                <input type="checkbox" class="form-check-input" id="ordersCheck1">
                                                <label class="form-check-label" for="ordersCheck1"></label>
                                            </div>
                                        </td>
                                        <td>{{ ++$nIndex }}</td>
                                        <td>{{ $page->name }}</td>
                                        <td>{{ $page->author->first_name . " " . $page->author->last_name }}</td>
                                        <td>
                                            <div class="btn-group" role="group">
                                                <a class="btn btn-dark btn-sm" href="{{ route('backend.page.edit', $page->id) }}">Edit</a>
                                                <!-- Button Group -->
                                                <div class="btn-group">
                                                    <button type="button"
                                                        class="btn btn-dark btn-icon btn-sm dropdown-toggle dropdown-toggle-empty"
                                                        id="ordersExportDropdown1" data-bs-toggle="dropdown"
                                                        aria-expanded="false"></button>
                                                    <div class="dropdown-menu dropdown-menu-end mt-1"
                                                        aria-labelledby="ordersExportDropdown1" style="">
                                                        <span class="dropdown-header">Options</span>
                                                        <div class="dropdown-divider"></div>
                                                        <form action="{{ route('backend.page.destroy', $page->id) }}" method="post">
                                                          @csrf
                                                          @method('delete')
                                                            <button class="dropdown-item text-danger" onclick="return confirm('Are you sure you want to delete this page?')" >Delete</button>
                                                        </form>
                                                    </div>
                                                </div>
                                                <!-- End Unfold -->
                                            </div>
                                            <!-- End Button -->
                                        </td>
                                    </tr>
                                @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection